#!/usr/bin/env ruby 
require "fileutils"
@tmpdir = "/tmp/csedir"
def openfile_p fname,mode
	FileUtils.mkdir_p(@tmpdir+File.dirname(fname))
	return File.open(@tmpdir+fname,mode)
end
headers = "
#include <iostream>
#include <string>
#include <map>
using namespace std;


map<string,string> resolveKeys(char* KeyString) {
    int P = 0;
    map<string,string> KeyMap;
    string Key = \"\";
    string Value = \"\";
    bool Mode = 1; // 0 = key, 1 = value
    while(KeyString[P]) {
        switch(KeyString[P]) {
        case '&':
            KeyMap[Key] = Value;
            Key = \"\";
            Value = \"\";
            Mode = 1;
            break;
        case '=':
            Mode = 0;
            break;
        default:
            if(Mode)
                Key += KeyString[P];
            else
                Value += KeyString[P];
        break;
        }
        P++;
    }
    KeyMap[Key] = Value;
    return KeyMap;
}

"
source = ""
source +=headers+"\n"
source += "int call(map<string,string> Request){
cout<< \"Content-Type: text/html\"<<endl;"
fname =  ARGV[0]
if File.exists?(@tmpdir+fname+".md5")
	res = `md5sum -c #{@tmpdir+fname+".md5"} 2> /dev/null`
	res = res.split(": ")[1]
	if res.strip=="OK"
		abort(`#{@tmpdir+ARGV[0]+".e"} #{ARGV[1]}`)
	end
else
	FileUtils.mkdir_p(@tmpdir+File.dirname(fname))
end
contents = File.open(fname,"rb").read
sections = contents.split("<%");
msections = []
sections.each do |o|
	o.split("%>").each do |s|
		msections << s;
	end
end
i=1
if contents.strip[0..1] == "<%"
	i=-1
end
firsttype = i;
cppsections = []
htmlsections = []
msections.each do |s|
	if i == -1
		cppsections << s
	else
		htmlsections << s
	end
	i*=-1
end
i = firsttype;
v = 1
c = 0
msections.each do
	begin
		if i == -1
			val = ""
			if cppsections[c][0]=='='
				val = "cout<<"+cppsections[c][1..-1]+";\n"
			else
				val = cppsections[c]
			end
			source += val
		else 
			source += "cout<<\"" +htmlsections[c].gsub("\"","\\\"").gsub("\n","\\n")+"\";\n";
		end
		if v == 2
			v = 0
			c+=1
		end
		v+=1
	rescue
	end
	i *= -1
end	

source += "}

int main(int argc, char**argv){
	if(argc==2)
	call(resolveKeys(argv[1]));	
	else
	call(resolveKeys(\"\"));
}

"

f=openfile_p(ARGV[0]+".cpp","w")
f.puts(source)
f.close
errmsg = `g++ -O2 #{@tmpdir+ARGV[0]+".cpp"} -o #{@tmpdir+ARGV[0]+".e"} 2>&1` 
if $? == 0
	t =`md5sum #{fname} > #{@tmpdir+fname+".md5"}`
		abort(`#{@tmpdir+ARGV[0]+".e"} #{ARGV[1]}`)
else
	puts "E#{errmsg}"
end
